// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToothPick.Models;

#nullable disable

namespace ToothPick.Migrations
{
    [DbContext(typeof(ToothPickContext))]
    [Migration("20211203160102_UpdateYoutubeDLL")]
    partial class UpdateYoutubeDLL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ToothPick.Models.Library", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("ToothPick.Models.Location", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyRegex")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaXPath")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "SerieName", "Url");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ToothPick.Models.Media", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePublished")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "SerieName", "Location");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePublished")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterLocation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "Name");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ToothPick.Models.Setting", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "Environment");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Name = "Environment",
                            Environment = "Default",
                            Value = "Debug"
                        },
                        new
                        {
                            Name = "ToothPickEnabled",
                            Environment = "Default",
                            Value = "True"
                        },
                        new
                        {
                            Name = "ChromeDriverLocation",
                            Environment = "Default",
                            Value = "resources"
                        },
                        new
                        {
                            Name = "FFMPEGLocation",
                            Environment = "Default",
                            Value = "resources/ffmpeg"
                        },
                        new
                        {
                            Name = "YoutubeDLLocation",
                            Environment = "Default",
                            Value = "resources/yt-dlp"
                        },
                        new
                        {
                            Name = "UserAgent",
                            Environment = "Default",
                            Value = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
                        },
                        new
                        {
                            Name = "DownloadPath",
                            Environment = "Default",
                            Value = "/Media"
                        },
                        new
                        {
                            Name = "ParallelChromes",
                            Environment = "Debug",
                            Value = "1"
                        },
                        new
                        {
                            Name = "ParallelChromes",
                            Environment = "Production",
                            Value = "4"
                        },
                        new
                        {
                            Name = "ParallelDownloads",
                            Environment = "Debug",
                            Value = "1"
                        },
                        new
                        {
                            Name = "ParallelDownloads",
                            Environment = "Production",
                            Value = "4"
                        },
                        new
                        {
                            Name = "ScanDelayMinutes",
                            Environment = "Debug",
                            Value = "0"
                        },
                        new
                        {
                            Name = "ScanDelayMinutes",
                            Environment = "Production",
                            Value = "5"
                        },
                        new
                        {
                            Name = "SkipNewSeries",
                            Environment = "Debug",
                            Value = "True"
                        },
                        new
                        {
                            Name = "SkipNewSeries",
                            Environment = "Production",
                            Value = "True"
                        },
                        new
                        {
                            Name = "ToothpickClientToken",
                            Environment = "Default",
                            Value = ""
                        },
                        new
                        {
                            Name = "ToothPickToken",
                            Environment = "Default",
                            Value = ""
                        },
                        new
                        {
                            Name = "ToothPickId",
                            Environment = "Default",
                            Value = ""
                        },
                        new
                        {
                            Name = "GotifyUri",
                            Environment = "Default",
                            Value = ""
                        },
                        new
                        {
                            Name = "GotifyHeader",
                            Environment = "Default",
                            Value = "X-Gotify-Key"
                        },
                        new
                        {
                            Name = "FixEpisodeNumbers",
                            Environment = "Default",
                            Value = "False"
                        },
                        new
                        {
                            Name = "DefaultXPath-1-youtube.com/playlist",
                            Environment = "Default",
                            Value = "//div[@id='contents']/ytd-playlist-video-renderer/div/div/ytd-thumbnail/a"
                        },
                        new
                        {
                            Name = "DefaultXPath-2-youtube.com",
                            Environment = "Default",
                            Value = "//div[@id='items']/ytd-grid-video-renderer/div/ytd-thumbnail/a"
                        },
                        new
                        {
                            Name = "DefaultKeyRegex-youtube.com/playlist",
                            Environment = "Default",
                            Value = "youtube\\.com\\/watch\\?v=(.*)&list"
                        },
                        new
                        {
                            Name = "DefaultKeyRegex-youtube.com",
                            Environment = "Default",
                            Value = "youtube\\.com\\/watch\\?v=(.*)&list"
                        });
                });

            modelBuilder.Entity("ToothPick.Models.Location", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Locations")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToothPick.Models.Serie", "Serie")
                        .WithMany("Locations")
                        .HasForeignKey("LibraryName", "SerieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("ToothPick.Models.Media", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Medias")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToothPick.Models.Serie", "Serie")
                        .WithMany("Medias")
                        .HasForeignKey("LibraryName", "SerieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Series")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("ToothPick.Models.Library", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Medias");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
