// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToothPick.Models;

namespace ToothPick.Migrations
{
    [DbContext(typeof(ToothPickContext))]
    [Migration("20210104013447_AddedSettings2")]
    partial class AddedSettings2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ToothPick.Models.Library", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("ToothPick.Models.Location", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "SerieName", "Url");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ToothPick.Models.Media", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("ThumbnailLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "SerieName", "Location");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.Property<string>("LibraryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryName", "Name");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ToothPick.Models.Setting", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "Environment");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Name = "Environment",
                            Environment = "Default",
                            Value = "Debug"
                        },
                        new
                        {
                            Name = "ToothPickEnabled",
                            Environment = "Default",
                            Value = "False"
                        },
                        new
                        {
                            Name = "ParallelChromes",
                            Environment = "Debug",
                            Value = "1"
                        },
                        new
                        {
                            Name = "ParallelChromes",
                            Environment = "Production",
                            Value = "4"
                        },
                        new
                        {
                            Name = "ParallelDownloads",
                            Environment = "Debug",
                            Value = "1"
                        },
                        new
                        {
                            Name = "ParallelDownloads",
                            Environment = "Production",
                            Value = "4"
                        },
                        new
                        {
                            Name = "ChromeDriverLocation",
                            Environment = "Debug",
                            Value = "resources"
                        },
                        new
                        {
                            Name = "ChromeDriverLocation",
                            Environment = "Production",
                            Value = "Resources"
                        },
                        new
                        {
                            Name = "FFMPEGLocation",
                            Environment = "Debug",
                            Value = "resources\\ffmpeg\\ffmpeg.exe"
                        },
                        new
                        {
                            Name = "FFMPEGLocation",
                            Environment = "Production",
                            Value = "Resources/ffmpeg/ffmpeg"
                        },
                        new
                        {
                            Name = "YoutubeDLLocation",
                            Environment = "Debug",
                            Value = "resources\\youtube-dl.exe"
                        },
                        new
                        {
                            Name = "YoutubeDLLocation",
                            Environment = "Production",
                            Value = "Resources/youtube-dl"
                        },
                        new
                        {
                            Name = "UserAgent",
                            Environment = "Default",
                            Value = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
                        },
                        new
                        {
                            Name = "DownloadPath",
                            Environment = "Debug",
                            Value = "videos"
                        },
                        new
                        {
                            Name = "DownloadPath",
                            Environment = "Production",
                            Value = "/srv/dev-disk-by-label-cctv/Media"
                        },
                        new
                        {
                            Name = "ScanDelayMinutes",
                            Environment = "Debug",
                            Value = "0"
                        },
                        new
                        {
                            Name = "ScanDelayMinutes",
                            Environment = "Production",
                            Value = "5"
                        },
                        new
                        {
                            Name = "SkipNewSeries",
                            Environment = "Debug",
                            Value = "True"
                        },
                        new
                        {
                            Name = "SkipNewSeries",
                            Environment = "Production",
                            Value = "True"
                        });
                });

            modelBuilder.Entity("ToothPick.Models.Location", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Locations")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToothPick.Models.Serie", "Serie")
                        .WithMany("Locations")
                        .HasForeignKey("LibraryName", "SerieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("ToothPick.Models.Media", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Medias")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToothPick.Models.Serie", "Serie")
                        .WithMany("Medias")
                        .HasForeignKey("LibraryName", "SerieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.HasOne("ToothPick.Models.Library", "Library")
                        .WithMany("Series")
                        .HasForeignKey("LibraryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("ToothPick.Models.Library", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Medias");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ToothPick.Models.Serie", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
